language: cpp
compiler:
  - gcc
addons:
  apt:
    packages:
      - libboost-random1.58-dev
      - libboost-system1.58-dev
      - libboost-test1.58-dev
      - libboost-thread1.58-dev
      - scons
env:
  global:
    - BOOST_INCLUDES=/usr/include
    - BOOST_LIBS=/usr/lib/x86_64-linux-gnu
script: scons -j 2 && scons test
branches:
  only:
    - master
    - develop
notifications:
  recipients:
    - travis@zaphoyd.com
  email:
    on_success: change
    on_failure: always
